version: "3.7"

services:
  app:
    image: hyperspeed/v1
    container_name: hyperspeed
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    restart: unless-stopped
    environment:
      - PORT=${PORT}
