version: "3.7"

services:
  app:
    image: feedbackform/v1
    container_name: feedback-form
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      FLAG: ${FLAG}